var MaterialUI = {
  Accordion: function () {},
  AccordionActions: function () {},
  AccordionDetails: function () {},
  AccordionSummary: function () {},
  Alert: function () {},
  AlertTitle: function () {},
  AppBar: function () {},
  Autocomplete: function () {},
  createFilterOptions: function () {},
  Avatar: function () {},
  Backdrop: function () {},
  Badge: function () {},
  BottomNavigation: function () {},
  BottomNavigationAction: function () {},
  Box: function () {},
  Breadcrumbs: function () {},
  Button: function () {},
  ButtonBase: function () {},
  ButtonGroup: function () {},
  Card: function () {},
  CardActionArea: function () {},
  CardActions: function () {},
  CardContent: function () {},
  CardHeader: function () {},
  CardMedia: function () {},
  Checkbox: function () {},
  Chip: function () {},
  CircularProgress: function () {},
  ClickAwayListener: function () {},
  Collapse: function () {},
  Container: function () {},
  CssBaseline: function () {},
  Dialog: function () {},
  DialogActions: function () {},
  DialogContent: function () {},
  DialogContentText: function () {},
  DialogTitle: function () {},
  Divider: function () {},
  Drawer: function () {},
  Fab: function () {},
  Fade: function () {},
  FilledInput: function () {},
  FormControl: function () {},
  useFormControl: function () {},
  FormControlLabel: function () {},
  FormGroup: function () {},
  FormHelperText: function () {},
  FormLabel: function () {},
  Grid: function () {},
  Grow: function () {},
  Hidden: function () {},
  Icon: function () {},
  IconButton: function () {},
  ImageList: function () {},
  ImageListItem: function () {},
  ImageListItemBar: function () {},
  Input: function () {},
  InputAdornment: function () {},
  InputBase: function () {},
  InputLabel: function () {},
  LinearProgress: function () {},
  Link: function () {},
  List: function () {},
  ListItem: function () {},
  ListItemAvatar: function () {},
  ListItemIcon: function () {},
  ListItemSecondaryAction: function () {},
  ListItemText: function () {},
  ListSubheader: function () {},
  Menu: function () {},
  MenuItem: function () {},
  MenuList: function () {},
  MobileStepper: function () {},
  Modal: function () {},
  ModalManager: function () {},
  NativeSelect: function () {},
  NoSsr: function () {},
  OutlinedInput: function () {},
  Pagination: function () {},
  PaginationItem: function () {},
  Paper: function () {},
  Popover: function () {},
  Popper: function () {},
  Portal: function () {},
  Radio: function () {},
  RadioGroup: function () {},
  useRadioGroup: function () {},
  Rating: function () {},
  ScopedCssBaseline: function () {},
  Select: function () {},
  Skeleton: function () {},
  Slide: function () {},
  Slider: function () {},
  Snackbar: function () {},
  SnackbarContent: function () {},
  SpeedDial: function () {},
  SpeedDialAction: function () {},
  SpeedDialIcon: function () {},
  Step: function () {},
  StepButton: function () {},
  StepConnector: function () {},
  StepContent: function () {},
  StepIcon: function () {},
  StepLabel: function () {},
  Stepper: function () {},
  SvgIcon: function () {},
  SwipeableDrawer: function () {},
  Switch: function () {},
  Tab: function () {},
  TabScrollButton: function () {},
  Table: function () {},
  TableBody: function () {},
  TableCell: function () {},
  TableContainer: function () {},
  TableFooter: function () {},
  TableHead: function () {},
  TablePagination: function () {},
  TableRow: function () {},
  TableSortLabel: function () {},
  Tabs: function () {},
  TextField: function () {},
  TextareaAutosize: function () {},
  ToggleButton: function () {},
  ToggleButtonGroup: function () {},
  Toolbar: function () {},
  Tooltip: function () {},
  Typography: function () {},
  Zoom: function () {},
  useAutocomplete: function () {},
  useMediaQuery: function () {},
  usePagination: function () {},
  useScrollTrigger: function () {}
};

var MaterialUIStyles = {
  adaptV4Theme: function () {},
  hexToRgb: function () {},
  rgbToHex: function () {},
  hslToRgb: function () {},
  decomposeColor: function () {},
  recomposeColor: function () {},
  getContrastRatio: function () {},
  getLuminance: function () {},
  emphasize: function () {},
  alpha: function () {},
  fade: function () {},
  darken: function () {},
  lighten: function () {},
  createMuiTheme: function () {},
  unstable_createMuiStrictModeTheme: function () {},
  createStyles: function () {},
  unstable_getUnit: function() {},
  unstable_toUnitless: function() {},
  makeStyles: function () {},
  responsiveFontSizes: function () {},
  styled: function () {},
  easing: {
    easeInOut: {},
    easeOut: {},
    easeIn: {},
    sharp: {}
  },
  duration: {
    shortest: {},
    shorter: {},
    short: {},
    standard: {},
    complex: {},
    enteringScreen: {},
    leavingScreen: {}
  },
  useTheme: function () {},
  withStyles: function () {},
  withTheme: function () {},
  createGenerateClassName: function () {},
  jssPreset: function () {},
  ServerStyleSheets: function () {},
  StylesProvider: function () {},
  MuiThemeProvider: function () {},
  ThemeProvider: function () {}
};

var MaterialUILab = {
  Alert: function () {},
  AlertTitle: function () {},
  Autocomplete: function () {},
  AvatarGroup: function () {},
  LoadingButton: function () {},
  Pagination: function () {},
  usePagination: function () {},
  PaginationItem: function () {},
  Rating: function () {},
  Skeleton: function () {},
  SliderStyled: function () {},
  SliderUnstyled: function () {},
  SpeedDial: function () {},
  SpeedDialAction: function () {},
  SpeedDialIcon: function () {},
  TabContext: function () {},
  TabList: function () {},
  TabPanel: function () {},
  Timeline: function () {},
  TimelineConnector: function () {},
  TimelineContent: function () {},
  TimelineDot: function () {},
  TimelineItem: function () {},
  TimelineOppositeContent: function () {},
  TimelineSeparator: function () {},
  ToggleButton: function () {},
  ToggleButtonGroup: function () {},
  TreeItem: function () {},
  useTreeItem: function () {},
  TreeView: function () {},
  useAutocomplete: function () {},
  createFilterOptions: function () {}
};

var MaterialUIPickers = {
  DatePicker: function () {},
  DesktopDatePicker: function () {},
  MobileDatePicker: function () {},
  StaticDatePicker: function () {},
  TimePicker: function () {},
  MobileTimePicker: function () {},
  DesktopTimePicker: function () {},
  StaticTimePicker: function () {},
  DateTimePicker: function () {},
  DesktopDateTimePicker: function () {},
  MobileDateTimePicker: function () {},
  StaticDateTimePicker: function () {},
  DateRangePicker: function () {},
  DesktopDateRangePicker: function () {},
  MobileDateRangePicker: function () {},
  StaticDateRangePicker: function () {},
  DateRangeDelimiter: function () {},
  LocalizationProvider: function () {}
};
