var MaterialUI = {
  createGenerateClassName: function () { },
  createMuiTheme: function () { },
  createStyles: function () { },
  jssPreset: function () { },
  makeStyles: function () { },
  MuiThemeProvider: function () { },
  responsiveFontSizes: function () { },
  ServerStyleSheets: function () { },
  styled: function () { },
  StylesProvider: function () { },
  ThemeProvider: function () { },
  useTheme: function () { },
  withStyles: function () { },
  withTheme: function () { },
  Accordion: function () { },
  AccordionActions: function () { },
  AccordionDetails: function () { },
  AccordionSummary: function () { },
  AppBar: function () { },
  Avatar: function () { },
  Backdrop: function () { },
  Badge: function () { },
  BottomNavigation: function () { },
  BottomNavigationAction: function () { },
  Box: function () { },
  Breadcrumbs: function () { },
  Button: function () { },
  ButtonBase: function () { },
  ButtonGroup: function () { },
  Card: function () { },
  CardActionArea: function () { },
  CardActions: function () { },
  CardContent: function () { },
  CardHeader: function () { },
  CardMedia: function () { },
  Checkbox: function () { },
  Chip: function () { },
  CircularProgress: function () { },
  ClickAwayListener: function () { },
  Collapse: function () { },
  Container: function () { },
  CssBaseline: function () { },
  Dialog: function () { },
  DialogActions: function () { },
  DialogContent: function () { },
  DialogContentText: function () { },
  DialogTitle: function () { },
  Divider: function () { },
  Drawer: function () { },
  ExpansionPanel: function () { },
  ExpansionPanelActions: function () { },
  ExpansionPanelDetails: function () { },
  ExpansionPanelSummary: function () { },
  Fab: function () { },
  Fade: function () { },
  FilledInput: function () { },
  FormControl: function () { },
  useFormControl: function () { },
  FormControlLabel: function () { },
  FormGroup: function () { },
  FormHelperText: function () { },
  FormLabel: function () { },
  Grid: function () { },
  GridList: function () { },
  GridListTile: function () { },
  GridListTileBar: function () { },
  Grow: function () { },
  Hidden: function () { },
  Icon: function () { },
  IconButton: function () { },
  Input: function () { },
  InputAdornment: function () { },
  InputBase: function () { },
  InputLabel: function () { },
  LinearProgress: function () { },
  Link: function () { },
  List: function () { },
  ListItem: function () { },
  ListItemAvatar: function () { },
  ListItemIcon: function () { },
  ListItemSecondaryAction: function () { },
  ListItemText: function () { },
  ListSubheader: function () { },
  Menu: function () { },
  MenuItem: function () { },
  MenuList: function () { },
  MobileStepper: function () { },
  Modal: function () { },
  ModalManager: function () { },
  NativeSelect: function () { },
  NoSsr: function () { },
  OutlinedInput: function () { },
  Paper: function () { },
  Popover: function () { },
  Popper: function () { },
  Portal: function () { },
  Radio: function () { },
  RadioGroup: function () { },
  useRadioGroup: function () { },
  RootRef: function () { },
  ScopedCssBaseline: function () { },
  Select: function () { },
  Slide: function () { },
  Slider: function () { },
  Snackbar: function () { },
  SnackbarContent: function () { },
  Step: function () { },
  StepButton: function () { },
  StepConnector: function () { },
  StepContent: function () { },
  StepIcon: function () { },
  StepLabel: function () { },
  Stepper: function () { },
  SvgIcon: function () { },
  SwipeableDrawer: function () { },
  Switch: function () { },
  Tab: function () { },
  TabScrollButton: function () { },
  Table: function () { },
  TableBody: function () { },
  TableCell: function () { },
  TableContainer: function () { },
  TableFooter: function () { },
  TableHead: function () { },
  TablePagination: function () { },
  TableRow: function () { },
  TableSortLabel: function () { },
  Tabs: function () { },
  TextField: function () { },
  TextareaAutosize: function () { },
  Toolbar: function () { },
  Tooltip: function () { },
  Typography: function () { },
  Zoom: function () { },
  useMediaQuery: function () { },
  useScrollTrigger: function () { },
};

var MaterialUIStyles = {
  hexToRgb: function () { },
  rgbToHex: function () { },
  hslToRgb: function () { },
  decomposeColor: function () { },
  recomposeColor: function () { },
  getContrastRatio: function () { },
  getLuminance: function () { },
  emphasize: function () { },
  fade: function () { },
  darken: function () { },
  lighten: function () { },
  createMuiTheme: function () { },
  createStyles: function () { },
  makeStyles: function () { },
  responsiveFontSizes: function () { },
  styled: function () { },
  easing: {
    easeInOut: { },
    easeOut: { },
    easeIn: { },
    sharp: { }
  },
  duration: {
    shortest: { },
    shorter: { },
    short: { },
    standard: { },
    complex: { },
    enteringScreen: { },
    leavingScreen: { }
  },
  formatMs: function () { },
  isString: function () { },
  isNumber: function () { },
  useTheme: function () { },
  withStyles: function () { },
  withTheme: function () { },
  createGenerateClassName: function () { },
  jssPreset: function () { },
  ServerStyleSheets: function () { },
  StylesProvider: function () { },
  MuiThemeProvider: function () { },
  ThemeProvider: function () { }
};

var MaterialUILab = {
  Alert: function () { },
  AlertTitle: function () { },
  Autocomplete: function () { },
  AvatarGroup: function () { },
  Pagination: function () { },
  usePagination: function () { },
  PaginationItem: function () { },
  Rating: function () { },
  Skeleton: function () { },
  SpeedDial: function () { },
  SpeedDialAction: function () { },
  SpeedDialIcon: function () { },
  Timeline: function () { },
  TimelineConnector: function () { },
  TimelineContent: function () { },
  TimelineDot: function () { },
  TimelineItem: function () { },
  TimelineOppositeContent: function () { },
  TimelineSeparator: function () { },
  ToggleButton: function () { },
  ToggleButtonGroup: function () { },
  TreeItem: function () { },
  TreeView: function () { },
  useAutocomplete: function () { },
};

var MaterialUIPickers = {
  Calendar: function () { },
  Clock: function () { },
  ClockView: function () { },
  DatePicker: function () { },
  DateTimePicker: function () { },
  Day: function () { },
  KeyboardDatePicker: function () { },
  KeyboardDateTimePicker: function () { },
  KeyboardTimePicker: function () { },
  MuiPickersContext: function () { },
  MuiPickersUtilsProvider: function () { },
  Picker: function () { },
  TimePicker: function () { },
  TimePickerView: function () { },
};
