name: CI

on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
      - next
  release:
    types:
      - created

env:
  NODE_VERSION: 16
  JAVA_VERSION: 17
  LEIN_VERSION: 2.9.4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: ${{ env.LEIN_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - run: npm ci
      - run: npm run test
      - run: lein cljfmt check

      - name: Build JS
        if: github.event_name == 'release'
        run: |
          lein clean
          npm run build

      - name: Deploy to Clojars
        if: github.event_name == 'release'
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: ./scripts/deploy.sh
